IF DB_ID(N'SISGIPAT') IS NULL
BEGIN
  PRINT 'Creando base SISGIPAT...';
  CREATE DATABASE SISGIPAT;
END
GO
ALTER DATABASE SISGIPAT SET RECOVERY SIMPLE;
ALTER DATABASE SISGIPAT SET ANSI_NULLS ON, QUOTED_IDENTIFIER ON;
GO
